-- create tables

CREATE TABLE COFFEE (ID NUMERIC(19) IDENTITY NOT NULL, NAME VARCHAR(255) NULL, PRICE FLOAT(32) NULL, PRIMARY KEY (ID))

CREATE TABLE COFFEE_AUDIT (AUDIT_ID NUMERIC(19) IDENTITY NOT NULL, COFFEE_ID NUMERIC(19) NOT NULL, NAME VARCHAR(255) NULL, PRICE FLOAT(32) NULL, PRIMARY KEY (AUDIT_ID))

-- create trigger
CREATE TRIGGER dbo.coffeetrigger on dbo.COFFEE 
AFTER INSERT
as BEGIN 
SET NOCOUNT ON;
INSERT INTO dbo.COFFEE_AUDIT(
        COFFEE_ID,
        NAME,
        PRICE
    )
    SELECT
        i.ID,
        i.NAME,
        i.PRICE
    FROM
        inserted i
END

-- drop trigger
-- DROP TRIGGER dbo.coffeetrigger

-- INSERT INTO [dbo].[COFFEE_AUDIT] ([COFFEE_ID], [NAME], [PRICE]) VALUES (1, 'COFFEE1', 11.1);
-- INSERT INTO [dbo].[COFFEE_AUDIT] ([COFFEE_ID], [NAME], [PRICE]) VALUES (2, 'COFFEE2', 22.2);
-- INSERT INTO [dbo].[COFFEE_AUDIT] ([COFFEE_ID], [NAME], [PRICE]) VALUES (3, 'COFFEE3', 33.3);
-- INSERT INTO [dbo].[COFFEE_AUDIT] ([COFFEE_ID], [NAME], [PRICE]) VALUES (4, 'COFFEE4', 44.4);
-- INSERT INTO [dbo].[COFFEE_AUDIT] ([COFFEE_ID], [NAME], [PRICE]) VALUES (5, 'COFFEE5', 55.5);